name: Library Release Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GITHUB_USERNAME: "meetacy"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY_CONTENTS }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

jobs:

  deploy-multiplatform:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.output_version.outputs.release_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Library Version to Env
        run: |
          release_version=$(./gradlew printVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Publish ${{ env.release_version }}
        run: ./gradlew publishKotlinMultiplatformPublicationToMavenCentralRepository
      - name: Add Library Version to Output
        id: output_version
        run: echo "release_version=${{ env.release_version }}" >> $GITHUB_OUTPUT

  deploy-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Library Version to Env
        run: |
          release_version=$(./gradlew printVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Publish ${{ env.release_version }}
        run: ./gradlew publishJvmPublicationToMavenCentralRepository

  deploy-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Library Version to Env
        run: |
          release_version=$(./gradlew printVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Publish ${{ env.release_version }}
        run: ./gradlew publishJsPublicationToMavenCentralRepository

  deploy-ios-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Konan Cache Setup
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: konan-cache
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Library Version to Env
        run: |
          release_version=$(./gradlew printVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Publish ${{ env.release_version }}
        run: ./gradlew publishIosX64PublicationToMavenCentralRepository

  deploy-ios-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Konan Cache Setup
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: konan-cache
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Library Version to Env
        run: |
          release_version=$(./gradlew printVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Publish ${{ env.release_version }}
        run: ./gradlew publishIosArm64PublicationToMavenCentralRepository

  deploy-ios-simulator-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Konan Cache Setup
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: konan-cache
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Library Version to Env
        run: |
          release_version=$(./gradlew printVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Publish ${{ env.release_version }}
        run: ./gradlew publishIosSimulatorArm64PublicationToMavenCentralRepository

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - deploy-multiplatform
      - deploy-jvm
      - deploy-js
      - deploy-ios-x64
      - deploy-ios-arm64
      - deploy-ios-simulator-arm64
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.deploy-multiplatform.outputs.release_version }}
          name: Release ${{ needs.deploy-multiplatform.outputs.release_version }}
